import "../styles/main.scss";
import { Inter } from "next/font/google";
import NavBar from "@/components/NabBar";
import SearchForm from "@/components/SearchForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avail ChatGPT-4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NavBar />
        <SearchForm />
        {children}
      </body>
    </html>
  );
}
