import "../styles/main.scss";
import Form from "@/components/Form";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avail ChatGPT-4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastContainer position='top-center' />
        <SideBar />
        <Form />
        {children}
      </body>
    </html>
  );
}
